version: "3.9"
services:
  app:
    image: app
    links:
      - "postgres:postgres"
    depends_on:
      - postgres
    ports:
      - "8082:8082"
  postgres:
    restart: always
    image: "postgres:alpine"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: bob
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: botppo
    volumes:
      - ./db/01-database-init.up.sql:/docker-entrypoint-initdb.d/01-database-init.up.sql
      - ./db/02-constraints.up.sql:/docker-entrypoint-initdb.d/02-constraints.up.sql